### ISSUE TITLE
Leaving in "2.3.3 :002 >"

### ISSUE THREAD

**Issue by victoriagrows-xx** [learn-co-curriculum/programming-univbasics-2-puts-prints-statements#2]
![image](https://user-images.githubusercontent.com/34456683/59486729-2e208100-8e2f-11e9-9d6a-0a5b668efa8d.png)
This is confusing to have in the example here. Was that an accident?

**Comment by maxwellbenton** [comment]
Hi @victoriagrows,

Thank you for providing this feedback. This may have been included to emphasize the difference between the `puts` and `print`, but I agree it is confusing as it isn't present elsewhere. We've updated this section, removed the IRB references in the code snippets to help clarify this which should help prevent confusion for future students.

Thank you for this contribution!

**Comment by victoriagrows-xx** [comment]
Great! Thanks.
